services:
    laravel.test:
        container_name: api
        build:
            context: './backend/vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './backend/.:/var/www/html'
        depends_on:
            database:
                condition: service_healthy
                restart: true

    database:
        container_name: database
        image: postgres
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            - POSTGRES_PASSWORD=MYSECRETPASSWORD
            - PGUSER=postgres
            - POSTGRES_DB=users_manager
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10
  
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080

networks:
  net:
    driver: overlay